name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # todo dia 00:00 UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Tyr700
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push Snake to output branch
        run: |
          cd dist
          git init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b output
          git add .
          git commit -m "Generate Snake"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Tyr700/Tyr700.git output
